<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Memorandum of Sale - Abodeology</title>
</head>
<body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;">
    <div style="background: #0F0F0F; padding: 20px; text-align: center; margin-bottom: 30px; border-radius: 8px;">
        <img src="{{ asset('media/abodeology-logo.png') }}" alt="Abodeology Logo" style="width: 160px; height: auto; object-fit: contain; max-width: 100%; display: block; margin: 0 auto;" onerror="this.style.display='none'; this.nextElementSibling.style.display='block';">
        <h1 style="color: #2CB8B4; margin: 0; display: none;">Abodeology®</h1>
    </div>

    <h2 style="color: #2CB8B4;">Memorandum of Sale</h2>

    <p>Dear {{ $recipientType === 'seller' ? $property->solicitor_name ?? 'Solicitor' : $offer->buyer->name }},</p>

    <p>A Memorandum of Sale has been generated for the property sale at <strong>{{ $property->address }}</strong>.</p>

    <div style="background: #F4F4F4; padding: 20px; border-radius: 8px; margin: 20px 0;">
        <h3 style="margin-top: 0; color: #2CB8B4;">Sale Details</h3>
        <p><strong>Property Address:</strong> {{ $property->address }}</p>
        @if($property->postcode)
            <p><strong>Postcode:</strong> {{ $property->postcode }}</p>
        @endif
        <p><strong>Agreed Sale Price:</strong> £{{ number_format($offer->offer_amount, 2) }}</p>
        <p><strong>Seller:</strong> {{ $property->seller->name }}</p>
        <p><strong>Buyer:</strong> {{ $offer->buyer->name }}</p>
        @if($offer->deposit_amount)
            <p><strong>Deposit Amount:</strong> £{{ number_format($offer->deposit_amount, 2) }}</p>
        @endif
        <p><strong>Accepted Date:</strong> {{ \Carbon\Carbon::now()->format('l, F j, Y') }}</p>
    </div>

    <div style="background: #E8F4F3; padding: 15px; margin: 20px 0; border-radius: 4px;">
        <p style="margin: 0;"><strong>Attachment:</strong> The Memorandum of Sale document is attached to this email for your records.</p>
    </div>

    <div style="background: #fff3cd; padding: 15px; margin: 20px 0; border-radius: 4px;">
        <p style="margin: 0; color: #856404;"><strong>Important:</strong> This Memorandum of Sale confirms the agreed terms but does not constitute a legally binding contract. A formal contract will need to be drawn up by the solicitors.</p>
    </div>

    <p><strong>Next Steps:</strong></p>
    <ul style="margin: 10px 0; padding-left: 25px;">
        <li>Both parties' solicitors should review the Memorandum of Sale</li>
        <li>Conveyancing process should commence</li>
        <li>All relevant documentation should be prepared</li>
        <li>Sales progression workflow has been initiated</li>
    </ul>

    <p>If you have any questions or require any additional information, please don't hesitate to contact us at <a href="mailto:support@abodeology.co.uk" style="color: #2CB8B4; text-decoration: none;">support@abodeology.co.uk</a>.</p>

    <p>Best regards,<br>
    <strong>The Abodeology Team</strong></p>

    <hr style="border: none; border-top: 1px solid #EAEAEA; margin: 30px 0;">
    <p style="font-size: 12px; color: #666; text-align: center;">
        © {{ date('Y') }} Abodeology®. All rights reserved.
    </p>
    <p style="font-size: 12px; color: #666; text-align: center;">
        This Memorandum of Sale has been automatically generated by the Abodeology platform.
    </p>
</body>
</html>
