<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Memorandum of Sale - Abodeology</title>
</head>
<body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;">
    <div style="background: #0F0F0F; padding: 20px; text-align: center; margin-bottom: 30px;">
        <h1 style="color: #2CB8B4; margin: 0;">Abodeology®</h1>
    </div>

    <h2 style="color: #2CB8B4;">Memorandum of Sale</h2>

    <p>Dear {{ $recipientType === 'seller' ? $property->solicitor_name ?? 'Solicitor' : $offer->buyer->name }},</p>

    <p>A Memorandum of Sale has been generated for the property sale at <strong>{{ $property->address }}</strong>.</p>

    <div style="background: #F4F4F4; padding: 20px; border-radius: 8px; margin: 20px 0;">
        <h3 style="margin-top: 0; color: #2CB8B4;">Sale Details</h3>
        <p><strong>Property Address:</strong> {{ $property->address }}</p>
        @if($property->postcode)
            <p><strong>Postcode:</strong> {{ $property->postcode }}</p>
        @endif
        <p><strong>Agreed Sale Price:</strong> £{{ number_format($offer->offer_amount, 2) }}</p>
        <p><strong>Seller:</strong> {{ $property->seller->name }}</p>
        <p><strong>Buyer:</strong> {{ $offer->buyer->name }}</p>
        @if($offer->deposit_amount)
            <p><strong>Deposit Amount:</strong> £{{ number_format($offer->deposit_amount, 2) }}</p>
        @endif
        <p><strong>Accepted Date:</strong> {{ \Carbon\Carbon::now()->format('l, F j, Y') }}</p>
    </div>

    <div style="background: #E8F4F3; padding: 15px; border-radius: 8px; margin: 20px 0;">
        <p style="margin: 0;"><strong>Attachment:</strong> The Memorandum of Sale document is attached to this email for your records.</p>
    </div>

    <div style="background: #fff3cd; border-left: 4px solid #ffc107; padding: 15px; margin: 20px 0;">
        <p style="margin: 0; color: #856404;"><strong>Important:</strong> This Memorandum of Sale confirms the agreed terms but does not constitute a legally binding contract. A formal contract will need to be drawn up by the solicitors.</p>
    </div>

    <p><strong>Next Steps:</strong></p>
    <ul>
        <li>Both parties' solicitors should review the Memorandum of Sale</li>
        <li>Conveyancing process should commence</li>
        <li>All relevant documentation should be prepared</li>
        <li>Sales progression workflow has been initiated</li>
    </ul>

    <p>If you have any questions or require any additional information, please don't hesitate to contact us.</p>

    <p>Best regards,<br>
    <strong>The Abodeology Team</strong></p>

    <div style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; text-align: center; color: #666; font-size: 12px;">
        <p>© {{ date('Y') }} Abodeology®. All rights reserved.</p>
        <p>This Memorandum of Sale has been automatically generated by the Abodeology platform.</p>
    </div>
</body>
</html>
